--EJEMPLO PROCEDURE
CREATE OR REPLACE PROCEDURE AUMENTAR_SALARIO(codEmp EMPLOYEES.EMPLOYEE_ID%TYPE, ratio NUMERIC)
LANGUAGE PLPGSQL	--DEBEMOS COLOCAR EL LENGUAJE
AS $$ --SUSTITUTO DE LAS COMILLAS
BEGIN
	--PODEMOS EJECUTAR SENTENCIAS SQL Y ACTUALIZAR DATOS: UPDATE, DELETE
	UPDATE EMPLOYEES SET SALARY = (1 + ratio) * SALARY
	WHERE EMPLOYEE_ID = codEmp;
END; $$--SUSTITUTO DE LAS COMILLAS


--PRUEBAS (BLOQUE ANOMIMO)
DO $$
BEGIN
	CALL AUMENTAR_SALARIO(101, 0.1); --LLAMADO A PROCEDURE
END; $$

--COMPROBACION DE RESULTADOS
select * from employees where employee_id = 101;


--EJEMPLO FUNCION
CREATE OR REPLACE FUNCTION SALARIO_TOTAL(codEmp EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURNS NUMERIC 	--ESPECIFICAMOS EL VALOR DE RETORNO
LANGUAGE PLPGSQL	--DEBEMOS COLOCAR EL LENGUAJE
AS
$$--SUSTITUTO DE LAS COMILLAS
DECLARE
	--BLOQUE DE DECLARACIONES
	salTotal NUMERIC;
BEGIN
	--PODEMOS CAPTURAR LOS RESULTADOS DE UNA CONSULTA EN VARIABLES
	SELECT SALARY * (1 + COALESCE(COMMISSION_PCT, 0))
	INTO salTotal
	FROM EMPLOYEES
	WHERE EMPLOYEE_ID = codEmp;	
	RETURN salTotal;
END;
$$--SUSTITUTO DE LAS COMILLAS

--CURSORES: BLOQUE ANONIMO
DO $$
DECLARE
	curEmp CURSOR 
	FOR SELECT * FROM EMPLOYEES; --DECLARACION
BEGIN
	FOR emp IN CurEmp LOOP --POR CADA ELEMENTO DEL CURSOR
		--PODEMOS UTILIZAR CUALQUIER ESTRUCTURA DE PROGRAMACION
		--VARIABLE emp REPRESENTA UNA TUPLA, PODEMOS ACCEDER A CADA VALOR DE COLUMNA
		IF emp.SALARY > 10000 AND emp.SALARY <= 15000  
       THEN
			RAISE NOTICE '% %', emp.LAST_NAME, emp.SALARY;
		END IF;
	END LOOP;
END;
$$

--CURSORES CON PARAMETROS
CREATE OR REPLACE PROCEDURE MOSTRAR_EMPLEADOS(nomCiudad LOCATIONS.CITY%TYPE)
LANGUAGE PLPGSQL
AS $$
DECLARE
	curEmp CURSOR(ciudad LOCATIONS.CITY%TYPE) FOR 
             SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE,
                    E.SALARY AS SALARIO,
				E.HIRE_DATE AS FECHA_CONT
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND L.LOCATION_ID = D.LOCATION_ID
AND L.CITY = ciudad;
BEGIN
	FOR emp IN curEmp(nomCiudad) LOOP
		RAISE NOTICE 'Empleado % . Salario: % / Fec. Contratacion: %', 
						emp.NOMBRE, emp.SALARIO, emp.FECHA_CONT;
	END LOOP;	
END; $$