
--INNER JOIN
SELECT * 
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--OUTER JOIN
SELECT COUNT(*)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--LEFT (OUTER) JOIN
SELECT 	E.FIRST_NAME || ' ' || E.LAST_NAME AS NOM,
		COALESCE(D.DEPARTMENT_NAME, 'SIN DPTO') AS DPTO
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NULL;

--UNION
SELECT EMPLOYEE_ID AS COD_EMP, FIRST_NAME AS NOM, LAST_NAME AS APE, SALARY AS SUELDO
FROM EMPLOYEES WHERE DEPARTMENT_ID = 90
UNION
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50, 90);


/*
	Muestre el nombre del empleado, el salario del empleado, el nombre del departamento al que pertenece, el nombre de 
	su rol y la ciudad donde trabaja
*/

SELECT 	E.FIRST_NAME, E.LAST_NAME, 
		E.SALARY, D.DEPARTMENT_NAME, J.JOB_TITLE,
		L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.JOB_ID = J.JOB_ID
AND D.LOCATION_ID = L.LOCATION_ID;



--NOMBRE DEL EMPLEADO, SALARIO, REGION, PAIS, CIUDAD, DEPARTAMENTO AL QUE PERTENECE

SELECT 	E.FIRST_NAME || ' ' || E.LAST_NAME AS NOM,
		E.SALARY AS SAL, R.REGION_NAME AS REG, C.COUNTRY_NAME AS PAIS,
		L.CITY AS CIUDAD, D.DEPARTMENT_NAME AS DPTO		
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, REGIONS R
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
AND L.COUNTRY_ID = C.COUNTRY_ID
AND C.REGION_ID = R.REGION_ID;

--FUNCIONES DE GRUPO
SELECT 	D.DEPARTMENT_NAME, TRUNC(AVG(E.SALARY), 2), 
		COUNT(*), SUM(E.SALARY), MAX(E.SALARY), 
		MIN(E.SALARY), MIN(E.HIRE_DATE)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.DEPARTMENT_ID <> 90
GROUP BY D.DEPARTMENT_NAME
HAVING AVG(E.SALARY) > 5000;



--FUNCIONES BD: CADENAS

SELECT 	LPAD(CAST(EMPLOYEE_ID AS VARCHAR), 10, '0'),
		LPAD(FIRST_NAME, 15, '*'),
		RPAD(FIRST_NAME, 15, '-'),
		FIRST_NAME || ' ' || LAST_NAME,
		UPPER(FIRST_NAME), LOWER(LAST_NAME),
		INITCAP(FIRST_NAME)		
FROM EMPLOYEES;

--FUNCIONES NUMERICAS
SELECT 	AVG(SALARY),
		TRUNC(AVG(SALARY)),
		ROUND(AVG(SALARY)) 
FROM EMPLOYEES;

SELECT 	AVG(SALARY),
		TRUNC(AVG(SALARY), 1),
		ROUND(AVG(SALARY), 1) 
FROM EMPLOYEES;

--USO DE 'LIKE'

--APELLIDOS QUE EMPIECEN CON 'A'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'A%';

--APELLIDOS QUE TERMINEN EN 'g'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%g';

--APELLIDOS QUE TENGAN 'n' COMO TERCERA LETRA
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '__n%';

--APELLIDOS QUE CONTENGAN LA CADENA 'ol'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%ol%';


--SUBCONSULTAS

--EMPLEADOS QUE GANAN MAS QUE EL PROMEDIO DE LA EMPRESA
SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--EMPLEADOS QUE GANAN MAS QUE EL PROMEDIO DE SU DEPARTAMENTO
SELECT * FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);

--NOMBRE DE EMPLEADO, SALARIO Y SALARIO PROMEDIO DE SU DEPARTAMENTO
SELECT 	E.LAST_NAME, E.SALARY, E.DEPARTMENT_ID,
		(SELECT TRUNC(AVG(SALARY), 2) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID)
FROM EMPLOYEES E;


SELECT E.LAST_NAME, E.SALARY, TRUNC(PROM.SAL_PROM, 2)
FROM 	EMPLOYEES E,
		( SELECT DEPARTMENT_ID, AVG(SALARY) AS SAL_PROM
		  FROM EMPLOYEES 
		  GROUP BY DEPARTMENT_ID ) PROM
WHERE E.DEPARTMENT_ID = PROM.DEPARTMENT_ID;

--FECHAS
SELECT MAX(HIRE_DATE), MIN(HIRE_DATE), MAX(HIRE_DATE) - MIN (HIRE_DATE)
FROM EMPLOYEES;

SELECT current_date - MAX(HIRE_DATE) FROM EMPLOYEES;

SELECT LAST_NAME, SALARY, HIRE_DATE, AGE(current_date, HIRE_DATE) FROM EMPLOYEES;

--EXTRACT: YEAR, MONTH, DAY
SELECT AGE(current_date, HIRE_DATE), EXTRACT(YEAR FROM AGE(current_date, HIRE_DATE)) FROM EMPLOYEES;

--NOMBRE DEL EMPLEADO Y NOMBRE DE SU SUPERVISOR: '<Empleado> esta a cargo de <Supervisor>'
SELECT 	E.FIRST_NAME || ' ' || E.LAST_NAME || ' esta a cargo de ' ||
		MGR.FIRST_NAME || ' ' || MGR.LAST_NAME
FROM EMPLOYEES E, EMPLOYEES MGR
WHERE E.MANAGER_ID = MGR.EMPLOYEE_ID

--EMPLEADOS CONTRATADOS A PARTIR DE 1994
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE >= TO_DATE('01/01/1994', 'DD/MM/YYYY');


--USO DE HAVING
SELECT REGION_NAME, COUNTRY_NAME, CITY, COUNT(*)
FROM EMP_FULL
GROUP BY REGION_NAME, COUNTRY_NAME, CITY
HAVING COUNT(*) > 5
ORDER BY COUNT(*) DESC;


-- CREAR UNA NUEVA TABLA CON EL CODIGO DE EMPLEADO COMPLETADO CON CEROS A LA IZQUIERDA (10 DIGITOS), EL NOMBRE COMPLETO 
-- DEL EMPLEADO Y EL SALARIO DEL MISMO. EXCLUYA A LOS EMPLEADOS DEL AREA EXECUTIVE

CREATE TABLE EMP001 AS (
						SELECT LPAD(CAST(E.EMPLOYEE_ID AS VARCHAR), 10, '0') AS COD,
							   E.FIRST_NAME || ' ' || E.LAST_NAME AS NOM,
							   E.SALARY AS SAL
						FROM EMPLOYEES E, DEPARTMENTS D
						WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
						AND D.DEPARTMENT_NAME <> 'Executive'
					   );

--USANDO VISTAS
CREATE VIEW EMP_VIEW AS (
						SELECT LPAD(CAST(E.EMPLOYEE_ID AS VARCHAR), 10, '0') AS COD,
							   E.FIRST_NAME || ' ' || E.LAST_NAME AS NOM,
							   E.SALARY AS SAL
						FROM EMPLOYEES E, DEPARTMENTS D
						WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
						AND D.DEPARTMENT_NAME <> 'Executive'
						);
						